document.addEventListener("DOMContentLoaded", function () {
    const tmData = [
            { number: "TM001", name: "Sheer Cold", recommendation: "Vender con NPC" },
            { number: "TM002", name: "Dragon Claw", recommendation: "Vender con NPC" },
            { number: "TM003", name: "Water Pulse", recommendation: "No es muy usado pero tal vez alguien lo comprará - Market o NPC" },
            { number: "TM004", name: "Psycho Cut", recommendation: "No es muy usado pero tal vez alguien lo comprará - Market o NPC" },
            { number: "TM005", name: "Roar", recommendation: "Vender con NPC" },
            { number: "TM006", name: "Toxic", recommendation: "Vender con NPC (Necesario para una misión)" },
            { number: "TM007", name: "Draco Meteor", recommendation: "Alguien lo comprará a buen precio - Market" },
            { number: "TM008", name: "Lava Plume", recommendation: "Alguien lo comprará a buen precio - Market" },
            { number: "TM009", name: "Bullet Seed", recommendation: "Alguien lo comprará a buen precio - Market" },
            { number: "TM010", name: "Rock Blast", recommendation: "Vender con NPC" },
            { number: "TM011", name: "Pursuit", recommendation: "Vender con NPC" },
            { number: "TM012", name: "Bug Buzz", recommendation: "No es muy usado pero tal vez alguien lo comprará - Market o NPC" },
            { number: "TM013", name: "Ice Beam", recommendation: "Vender con NPC" },
            { number: "TM014", name: "Blizzard", recommendation: "Alguien lo comprará a buen precio - Market" },
            { number: "TM015", name: "Hyper Beam", recommendation: "Vender con NPC" },
            { number: "TM016", name: "Ancient Power", recommendation: "Vender con NPC" },
            { number: "TM017", name: "Doom Desire", recommendation: "Alguien lo comprará a buen precio - Market" },
            { number: "TM018", name: "Rain Dance", recommendation: "Alguien lo comprará a buen precio - Market" },
            { number: "TM019", name: "Giga Drain", recommendation: "Vender con NPC" },
            { number: "TM020", name: "Frenzy Plant", recommendation: "No es muy usado pero tal vez alguien lo comprará - Market o NPC" },
            { number: "TM021", name: "Fly Attack", recommendation: "Vender con NPC" },
            { number: "TM022", name: "Solar Beam", recommendation: "Vender con NPC" },
            { number: "TM023", name: "Meteor Mash", recommendation: "No es muy usado pero tal vez alguien lo comprará - Market o NPC" },
            { number: "TM024", name: "Thunder Bolt", recommendation: "Vender con NPC" },
            { number: "TM025", name: "Thunder", recommendation: "Vender con NPC" },
            { number: "TM026", name: "Earthquake", recommendation: "Alguien lo comprará aunque no es tan valuado - Market" },
            { number: "TM027", name: "Dark Pulse", recommendation: "Alguien lo comprará aunque no es tan valuado - Market" },
            { number: "TM028", name: "X-Scissor", recommendation: "Vender con NPC" },
            { number: "TM029", name: "Psychic", recommendation: "No es muy usado pero tal vez alguien lo comprará - Market o NPC" },
            { number: "TM030", name: "Shadow Ball", recommendation: "Vender con NPC" },
            { number: "TM031", name: "Brick Break", recommendation: "Alguien lo comprará aunque no es tan valuado - Market" },
            { number: "TM032", name: "Tri Attack", recommendation: "Vender con NPC" },
            { number: "TM033", name: "Reflect", recommendation: "Alguien lo comprará a buen precio - Market" },
            { number: "TM034", name: "Bulldoze", recommendation: "Vender con NPC" },
            { number: "TM035", name: "Flamethrower", recommendation: "Vender con NPC" },
            { number: "TM036", name: "Sludge Rain", recommendation: "Alguien lo comprará a buen precio - Market" },
            { number: "TM037", name: "Sandstorm", recommendation: "Alguien lo comprará aunque no es tan valuado - Market" },
            { number: "TM038", name: "Fire Blast", recommendation: "Vender con NPC (Necesario para una misión)" },
            { number: "TM039", name: "Discharge", recommendation: "Alguien lo comprará a buen precio - Market" },
            { number: "TM040", name: "Aerial Ace", recommendation: "Vender con NPC" },
            { number: "TM041", name: "Sky Uppercut", recommendation: "No es muy usado pero tal vez alguien lo comprará - Market o NPC" },
            { number: "TM042", name: "Crunch", recommendation: "Vender con NPC" },
            { number: "TM043", name: "Dragon Pulse", recommendation: "Vender con NPC" },
            { number: "TM044", name: "Fissure", recommendation: "Alguien lo comprará aunque no es tan valuado - Market" },
            { number: "TM045", name: "Attract", recommendation: "Vender con NPC" },
            { number: "TM046", name: "Hydropump", recommendation: "Alguien lo comprará aunque no es tan valuado - Market" },
            { number: "TM047", name: "Steel Wing", recommendation: "No es muy usado pero tal vez alguien lo comprará - Market o NPC" },
            { number: "TM048", name: "Shadow Storm", recommendation: "Alguien lo comprará a buen precio - Market" },
            { number: "TM049", name: "Beat Up", recommendation: "Alguien lo comprará aunque no es tan valuado - Market" },
            { number: "TM050", name: "Overheat", recommendation: "Vender con NPC" },
            { number: "TM051", name: "Icebreaker", recommendation: "Vender con NPC" },
            { number: "TM052", name: "Aqua Jet", recommendation: "Vender con NPC" },
            { number: "TM053", name: "Power Split", recommendation: "Vender con NPC" },
            { number: "TM054", name: "Super Power", recommendation: "Alguien lo comprará a buen precio - Market" },
            { number: "TM055", name: "Rock Smash", recommendation: "Alguien lo comprará aunque no es tan valuado - Market" },
            { number: "TM056", name: "Sky Attack", recommendation: "No es muy usado pero tal vez alguien lo comprará - Market o NPC" },
            { number: "TM057", name: "Tornado", recommendation: "Alguien lo comprará aunque no es tan valuado - Market" },
            { number: "TM058", name: "Shadow Blast", recommendation: "Alguien lo comprará a buen precio - Market" },
            { number: "TM059", name: "Venom Blast", recommendation: "Alguien lo comprará aunque no es tan valuado - Market" },
            { number: "TM060", name: "Poison Gas", recommendation: "Alguien lo comprará aunque no es tan valuado - Market" },
            { number: "TM061", name: "Gunk Shot", recommendation: "Vender con NPC" },
            { number: "TM062", name: "Mud Bomb", recommendation: "No es muy usado pero tal vez alguien lo comprará - Market o NPC" },
            { number: "TM063", name: "Rock Slide", recommendation: "Vender con NPC" },
            { number: "TM064", name: "Struggle Bug", recommendation: "Vender con NPC" },
            { number: "TM065", name: "Infestation", recommendation: "Alguien lo comprará a buen precio - Market" },
            { number: "TM066", name: "Parabolic Charge", recommendation: "Vender con NPC (Necesario para una misión)" },
            { number: "TM067", name: "Wild Charge", recommendation: "Vender con NPC" },
            { number: "TM068", name: "Dragon Rush", recommendation: "Vender con NPC" },
            { number: "TM069", name: "Petal Blizzard", recommendation: "Alguien lo comprará a buen precio - Market" },
            { number: "TM070", name: "Flash Cannon", recommendation: "Vender con NPC" },
            { number: "TM071", name: "Double Team", recommendation: "Vender con NPC" },
            { number: "TM072", name: "Dizzy Punch", recommendation: "Vender con NPC" },
            { number: "TM073", name: "Feint", recommendation: "Alguien lo comprará aunque no es tan valuado - Market" },
            { number: "TM074", name: "Falling Rocks", recommendation: "Alguien lo comprará a buen precio - Market" },
            { number: "TM075", name: "Ice Storm", recommendation: "Alguien lo comprará a buen precio - Market" },
            { number: "TM076", name: "Last Resort", recommendation: "Vender con NPC" },
            { number: "TM077", name: "Venom Storm", recommendation: "Alguien lo comprará aunque no es tan valuado - Market" },
            { number: "TM078", name: "Eruption", recommendation: "Alguien lo comprará aunque no es tan valuado - Market" },
            { number: "TM079", name: "Metal Burst", recommendation: "No es muy usado pero tal vez alguien lo comprará - Market o NPC" },
            { number: "TM080", name: "Whirlpool", recommendation: "Alguien lo comprará (necesario para misión)" },
            { number: "TM081", name: "Dragon Wave", recommendation: "Vender con NPC" },
            { number: "TM082", name: "Nuzzle", recommendation: "Vender con NPC" },
            { number: "TM083", name: "Grassy Terrain", recommendation: "No es muy usado pero tal vez alguien lo comprará - Market o NPC" },
            { number: "TM084", name: "Moon Blast", recommendation: "Vender con NPC" },
            { number: "TM085", name: "Night Daze", recommendation: "Alguien lo comprará a buen precio - Market" },
            { number: "TM086", name: "Fake Tears", recommendation: "Vender con NPC" },
            { number: "TM087", name: "Poison Jab", recommendation: "Vender con NPC" },
            { number: "TM088", name: "Air Shot", recommendation: "Vender con NPC" },
            { number: "TM089", name: "Mud", recommendation: "Vender con NPC" },
            { number: "TM090", name: "Icicle Spear", recommendation: "Vender con NPC" },
            { number: "TM091", name: "Dazzling Gleam", recommendation: "Alguien lo comprará aunque no es tan valuado - Market" },
            { number: "TM092", name: "Play Rough", recommendation: "Vender con NPC" },
            { number: "TM093", name: "Rock Polish", recommendation: "Vender con NPC" },
            { number: "TM094", name: "Disarming Voice", recommendation: "No es muy usado pero tal vez alguien lo comprará - Market o NPC" },
            { number: "TM095", name: "Pound", recommendation: "Vender con NPC" },
            { number: "TM096", name: "Stored Power", recommendation: "Vender con NPC" },
            { number: "TM097", name: "Metal Sound", recommendation: "No es muy usado pero tal vez alguien lo comprará - Market o NPC" },
            { number: "TM098", name: "Baby-Doll Eyes", recommendation: "Vender con NPC" },
            { number: "TM099", name: "Quiver Dance", recommendation: "Alguien lo comprará aunque no es tan valuado - Market" },
            { number: "TM100", name: "Fairy Wind", recommendation: "Alguien lo comprará a buen precio - Market" },
            { number: "TM101", name: "Epicenter", recommendation: "Alguien lo comprará a buen precio - Market" },
            { number: "TM102", name: "Psyblast", recommendation: "Alguien lo comprará a buen precio - Market" },
            { number: "TM103", name: "Reversal", recommendation: "Alguien lo comprará aunque no es tan valuado - Market" },
            { number: "TM104", name: "Blast Burner", recommendation: "Alguien lo comprará a buen precio - Marke" },
            { number: "TM105", name: "Circular Explosion", recommendation: "Alguien lo comprará aunque no es tan valuado - Market" },
            { number: "TM106", name: "Boomburst", recommendation: "Alguien lo comprará aunque no es tan valuado - Market" },
            { number: "TM107", name: "Chip Away", recommendation: "Vender con NPC" },
            { number: "TM108", name: "Echoed Voice", recommendation: "No es muy usado pero tal vez alguien lo comprará - Market o NPC" },
            { number: "TM109", name: "Play Nice", recommendation: "Vender con NPC" },
            { number: "TM110", name: "Sleep Talk", recommendation: "No es muy usado pero tal vez alguien lo comprará - Market o NPC" },
            { number: "TM111", name: "Fire Pledge", recommendation: "Vender con NPC" },
            { number: "TM112", name: "Flame Blitz", recommendation: "Alguien lo comprará aunque no es tan valuado - Market" },
            { number: "TM113", name: "Force Palm", recommendation: "Alguien lo comprará a buen precio - Marke" },
            { number: "TM114", name: "Bulk Up", recommendation: "No es muy usado pero tal vez alguien lo comprará - Market o NPC" },
            { number: "TM115", name: "Brine", recommendation: "No es muy usado pero tal vez alguien lo comprará - Market o NPC" },
            { number: "TM116", name: "Liquidation", recommendation: "No es muy usado pero tal vez alguien lo comprará - Market o NPC" },
            { number: "TM117", name: "Surf", recommendation: "Vender con NPC" },
            { number: "TM118", name: "Tsunami", recommendation: "No es muy usado pero tal vez alguien lo comprará - Market o NPC" },
            { number: "TM119", name: "Air Pressure", recommendation: "Alguien lo comprará aunque no es tan valuado - Market" },
            { number: "TM120", name: "Hurricane", recommendation: "Alguien lo comprará aunque no es tan valuado - Market" },
            { number: "TM121", name: "Fascade", recommendation: "Vender con NPC" },
            { number: "TM122", name: "Grass Whistle", recommendation: "No es muy usado pero tal vez alguien lo comprará - Market o NPC" },
            { number: "TM123", name: "Magical Leaf", recommendation: "Alguien lo comprará aunque no es tan valuado - Market" },
            { number: "TM124", name: "Power Whip", recommendation: "No es muy usado pero tal vez alguien lo comprará - Market o NPC" },
            { number: "TM125", name: "Venoshock", recommendation: "Alguien lo comprará aunque no es tan valuado - Market" },
            { number: "TM126", name: "Venom Drench", recommendation: "Vender con NPC" },
            { number: "TM127", name: "Electric Storm", recommendation: "Alguien lo comprará a buen precio - Market" },
            { number: "TM128", name: "Eerie Impulse", recommendation: "Alguien lo comprará aunque no es tan valuado - Market" },
            { number: "TM129", name: "Electro Blast", recommendation: "Alguien lo comprará aunque no es tan valuado - Market" },
            { number: "TM130", name: "Magnitude", recommendation: "No es muy usado pero tal vez alguien lo comprará - Market o NPC" },
            { number: "TM131", name: "Thousand Arrows", recommendation: "Vender con NPC" },
            { number: "TM132", name: "Psychic Terrain", recommendation: "No es muy usado pero tal vez alguien lo comprará - Market o NPC" },
            { number: "TM133", name: "Synchronoise", recommendation: "Alguien lo comprará a buen precio - Market" },
            { number: "TM134", name: "Rock Storm", recommendation: "Alguien lo comprará a buen precio - Market" },
            { number: "TM135", name: "Rock Power", recommendation: "No es muy usado pero tal vez alguien lo comprará - Market o NPC" },
            { number: "TM136", name: "Aurora Veil", recommendation: "Vender con NPC" },
            { number: "TM137", name: "Ice Shards", recommendation: "Alguien lo comprará a buen precio - Market" },
            { number: "TM138", name: "Aurora Sphere", recommendation: "Vender con NPC" },
            { number: "TM139", name: "Lunge", recommendation: "Alguien lo comprará a buen precio - Market" },
            { number: "TM140", name: "Rage Powder", recommendation: "Vender con NPC" },
            { number: "TM141", name: "U Turn", recommendation: "Vender con NPC" },
            { number: "TM142", name: "Clanging Scales", recommendation: "No es muy usado pero tal vez alguien lo comprará - Market o NPC" },
            { number: "TM143", name: "Dragon Storm", recommendation: "Alguien lo comprará a buen precio - Market" },
            { number: "TM144", name: "Draco Pulse", recommendation: "Vender con NPC" },
            { number: "TM145", name: "Twister", recommendation: "Alguien lo comprará aunque no es tan valuado - Market" },
            { number: "TM146", name: "Ominous Wind", recommendation: "Vender con NPC" },
            { number: "TM147", name: "Curse Pledge", recommendation: "Alguien lo comprará aunque no es tan valuado - Market" },
            { number: "TM148", name: "Grudge", recommendation: "No es muy usado pero tal vez alguien lo comprará - Market o NPC" },
            { number: "TM149", name: "Shadow Claw", recommendation: "No es muy usado pero tal vez alguien lo comprará - Market o NPC" },
            { number: "TM150", name: "Snarl", recommendation: "Alguien lo comprará a buen precio - Market" },
            { number: "TM151", name: "Brutal Swing", recommendation: "Vender con NPC" },
            { number: "TM152", name: "Magnetic Shock", recommendation: "Alguien lo comprará a buen precio - Market" },
            { number: "TM153", name: "Gear Grind", recommendation: "No es muy usado pero tal vez alguien lo comprará - Market o NPC" },
            { number: "TM154", name: "Smart Strike", recommendation: "Vender con NPC" },
            { number: "TM155", name: "Misty Terrain", recommendation: "Alguien lo comprará aunque no es tan valuado - Market" },
            { number: "TM156", name: "Fairy Blade", recommendation: "No es muy usado pero tal vez alguien lo comprará - Market o NPC" },
            { number: "TM157", name: "Defog", recommendation: "Alguien lo comprará a buen precio - Market" },
            { number: "TM158", name: "Water Tornado", recommendation: "Alguien lo comprará a buen precio - Market" },
            { number: "TM159", name: "Wonder Room", recommendation: "Alguien lo comprará aunque no es tan valuado - Market" },
            { number: "TM160", name: "Mud Sport", recommendation: "Vender con NPC" },
            { number: "TM161", name: "Magma Storm", recommendation: "Alguien lo comprará a buen precio - Market" },
            { number: "TM162", name: "Tectonic Dance", recommendation: "Alguien lo comprará a buen precio - Market" },
            { number: "TM163", name: "Fury Swipes", recommendation: "Alguien lo comprará aunque no es tan valuado - Market" },
            { number: "TM164", name: "Steamroller", recommendation: "Alguien lo comprará a buen precio - Market" },
            { number: "TM165", name: "Mist", recommendation: "Alguien lo comprará a buen precio - Market" },
            { number: "TM166", name: "Dragon Cry", recommendation: "Alguien lo comprará aunque no es tan valuado - Market" },
            { number: "TM167", name: "Burn Up", recommendation: "Vender con NPC" },
            { number: "TM168", name: "Dream Catcher", recommendation: "Alguien lo comprará aunque no es tan valuado - Market" },
            { number: "TM169", name: "Fairy Dreams", recommendation: "Alguien lo comprará aunque no es tan valuado - Market" },
            { number: "TM170", name: "Ghost Drive", recommendation: "Vender con NPC" },
            { number: "TM171", name: "Spiritual Storm", recommendation: "No es muy usado pero tal vez alguien lo comprará - Market o NPC" },
            { number: "TM172", name: "Grass Knot", recommendation: "Alguien lo comprará aunque no es tan valuado - Market" },
            { number: "TM173", name: "Geomancy", recommendation: "No es muy usado pero tal vez alguien lo comprará - Market o NPC" },
            { number: "TM174", name: "Shift Gear", recommendation: "Alguien lo comprará a buen precio - Market" },
            { number: "TM175", name: "Light of Ruin", recommendation: "Alguien lo comprará a buen precio - Market" },
            { number: "TM176", name: "Natural Gift", recommendation: "Alguien lo comprará aunque no es tan valuado - Market" },
            { number: "TM177", name: "Selfdestruction", recommendation: "Alguien lo comprará aunque no es tan valuado - Market" },
            { number: "TM178", name: "Final Gambit", recommendation: "Alguien lo comprará aunque no es tan valuado - Market" },
            { number: "TM179", name: "Embargo", recommendation: "Alguien lo comprará a buen precio - Market" },
            { number: "TM180", name: "Sizzly Slide", recommendation: "Alguien lo comprará aunque no es tan valuado - Market" },
            { number: "TM181", name: "Spin Out", recommendation: "Alguien lo comprará aunque no es tan valuado - Market" },
            { number: "TM182", name: "Leaf Storm", recommendation: "Alguien lo comprará a buen precio - Market" },
            { number: "TM183", name: "Leaf Tornado", recommendation: "Alguien lo comprará a buen precio - Market" },
            { number: "TM184", name: "Spite", recommendation: "Vender con NPC" },
            { number: "TM185", name: "Stone Edge", recommendation: "Alguien lo comprará a buen precio - Market" },
            { number: "TM186", name: "Close Combat", recommendation: "Vender con NPC" },
            { number: "TM187", name: "Sky Drop", recommendation: "Vender con NPC" },
            { number: "TM188", name: "Flame Charge", recommendation: "Vender con NPC" },
            { number: "TM189", name: "Metallic Noise", recommendation: "Alguien lo comprará aunque no es tan valuado - Market" },
            { number: "TM190", name: "Freeze Dry", recommendation: "Alguien lo comprará aunque no es tan valuado - Market" },
            { number: "TM191", name: "Electric Terrain", recommendation: "No es muy usado pero tal vez alguien lo comprará - Market o NPC" },
            { number: "TM192", name: "Trick Room", recommendation: "No es muy usado pero tal vez alguien lo comprará - Market o NPC" },
            { number: "TM193", name: "Foul Play", recommendation: "Alguien lo comprará aunque no es tan valuado - Market" },
            { number: "TM194", name: "Mean Look", recommendation: "Alguien lo comprará aunque no es tan valuado - Market" },
            { number: "TM195", name: "Lava Pulse", recommendation: "Alguien lo comprará aunque no es tan valuado - Market" },
            { number: "TM196", name: "Brave Bird", recommendation: "No es muy usado pero tal vez alguien lo comprará - Market o NPC" },
            { number: "TM197", name: "Selfheal", recommendation: "No es muy usado pero tal vez alguien lo comprará - Market o NPC" },
            { number: "TM198", name: "Toxic Drop", recommendation: "No es muy usado pero tal vez alguien lo comprará - Market o NPC" },
            { number: "TM199", name: "Metronome", recommendation: "Vender con NPC" },
            { number: "TM200", name: "Mimic", recommendation: "No es muy usado pero tal vez alguien lo comprará - Market o NPC" },
            { number: "TM201", name: "Submission", recommendation: "Alguien lo comprará aunque no es tan valuado - Market" },
            { number: "TM202", name: "Fling", recommendation: "Alguien lo comprará aunque no es tan valuado - Market" },
            { number: "TM203", name: "Flutterby", recommendation: "No es muy usado pero tal vez alguien lo comprará - Market o NPC" },
            { number: "TM204", name: "Toxication", recommendation: "Alguien lo comprará aunque no es tan valuado - Market" },
            { number: "TM205", name: "Entrainment", recommendation: "Vender con NPC" },
            { number: "TM206", name: "Lightning Storm", recommendation: "Alguien lo comprará aunque no es tan valuado - Market" },
            { number: "TM207", name: "Airstream", recommendation: "Alguien lo comprará aunque no es tan valuado - Market" },
            { number: "TM208", name: "Twinkle Star", recommendation: "Alguien lo comprará a buen precio - Market" },
            { number: "TM209", name: "Dragon Lullaby", recommendation: "No es muy usado pero tal vez alguien lo comprará - Market o NPC" },
            { number: "TM210", name: "Chi Strike", recommendation: "No es muy usado pero tal vez alguien lo comprará - Market o NPC" },
            { number: "TM211", name: "Smack Down", recommendation: "Vender con NPC" },
            { number: "TM212", name: "Quicksand", recommendation: "Alguien lo comprará aunque no es tan valuado - Market" },
            { number: "TM213", name: "Electrify", recommendation: "Alguien lo comprará aunque no es tan valuado - Market" },
            { number: "TM214", name: "Stone Crash", recommendation: "No es muy usado pero tal vez alguien lo comprará - Market o NPC" },
            { number: "TM215", name: "Light Screen", recommendation: "Alguien lo comprará aunque no es tan valuado - Market" },
            { number: "TM216", name: "Metallic Rush", recommendation: "Alguien lo comprará aunque no es tan valuado - Market" },
            { number: "TM217", name: "Triple Axel", recommendation: "Alguien lo comprará a buen precio - Market" },
            { number: "TM218", name: "Corrosive Gas", recommendation: "Alguien lo comprará a buen precio - Market" },
            { number: "TM219", name: "Eagle Fury", recommendation: "No es muy usado pero tal vez alguien lo comprará - Market o NPC" },
            { number: "TM220", name: "Sand Force", recommendation: "Alguien lo comprará aunque no es tan valuado - Market" },
            { number: "TM221", name: "Lash Out", recommendation: "No es muy usado pero tal vez alguien lo comprará - Market o NPC" },
            { number: "TM222", name: "Imprison", recommendation: "Alguien lo comprará aunque no es tan valuado - Market" },
            { number: "TM223", name: "Night Shade", recommendation: "No es muy usado pero tal vez alguien lo comprará - Market o NPC" },
            { number: "TM224", name: "Overgrowth", recommendation: "No es muy usado pero tal vez alguien lo comprará - Market o NPC" },
            { number: "TM225", name: "Meteor Beam", recommendation: "Alguien lo comprará a buen precio - Market" },
            { number: "TM226", name: "Scorching Sands", recommendation: "Alguien lo comprará aunque no es tan valuado - Market" },
            { number: "TM227", name: "Deadly Scythes", recommendation: "Alguien lo comprará a buen precio - Market" },
            { number: "TM228", name: "Fiery Tornado", recommendation: "Alguien lo comprará a buen precio - Market" },
            { number: "TM229", name: "Muddy Water", recommendation: "Vender con NPC" },
            { number: "TM230", name: "Outrage", recommendation: "Alguien lo comprará aunque no es tan valuado - Market" },
            { number: "TM231", name: "Aqua Blast", recommendation: "Vender con NPC" },
            { number: "TM232", name: "Water Swirl", recommendation: "Alguien lo comprará a buen precio - Market" },
            { number: "TM233", name: "Volt Rush", recommendation: "Alguien lo comprará aunque no es tan valuado - Market" },
            { number: "TM234", name: "Fairy Pillar", recommendation: "Alguien lo comprará aunque no es tan valuado - Market" },
            { number: "TM235", name: "Steelsurge", recommendation: "Alguien lo comprará aunque no es tan valuado - Market" },
            { number: "TM236", name: "Toxic Cloud", recommendation: "Alguien lo comprará aunque no es tan valuado - Market" },
            { number: "TM237", name: "Psycho Burst", recommendation: "Alguien lo comprará aunque no es tan valuado - Market" },
            { number: "TM238", name: "Terrain Strike", recommendation: "No es muy usado pero tal vez alguien lo comprará - Market o NPC" },
            { number: "TM239", name: "Glacial Impale", recommendation: "Alguien lo comprará a buen precio - Market" },
            { number: "TM240", name: "X-Cutter", recommendation: "Alguien lo comprará a buen precio - Market" },
            { number: "TM241", name: "Endless Nightmare", recommendation: "Alguien lo comprará a buen precio - Market" },
            { number: "TM242", name: "Sleeping Powder", recommendation: "Alguien lo comprará aunque no es tan valuado - Market" },
            { number: "TM243", name: "Brutal Beatdown", recommendation: "Alguien lo comprará a buen precio - Market" },
            { number: "TM244", name: "Stone Axe", recommendation: "Alguien lo comprará a buen precio - Market" },
            { number: "TM245", name: "Ghastly Devastation", recommendation: "Alguien lo comprará a buen precio - Market" },
            { number: "TM246", name: "Mountain Gale", recommendation: "Alguien lo comprará aunque no es tan valuado - Market" },
            { number: "TM247", name: "Shadow Fury", recommendation: "Alguien lo comprará aunque no es tan valuado - Market" },
            { number: "TM248", name: "Bloom Doom", recommendation: "Alguien lo comprará a buen precio - Market" },
            { number: "TM249", name: "Sandblast", recommendation: "Alguien lo comprará a buen precio - Market" },
            { number: "TM250", name: "Wind Rage", recommendation: "Alguien lo comprará aunque no es tan valuado - Market" },
            { number: "TM251", name: "10mil Thunder Bolt", recommendation: "Alguien lo comprará a buen precio - Market" },
            { number: "TM252", name: "Toxic Torrent", recommendation: "Alguien lo comprará aunque no es tan valuado - Market" },
            { number: "TM253", name: "Upper Hand", recommendation: "Alguien lo comprará a buen precio - Market" },
            { number: "TM254", name: "Pyro Pulse", recommendation: "Alguien lo comprará a buen precio - Market" },
            { number: "TM255", name: "Telekinetic Thrust", recommendation: "Alguien lo comprará a buen precio - Market" },
            { number: "TM256", name: "Draco Comet", recommendation: "Alguien lo comprará aunque no es tan valuado - Market" },
            { number: "TM257", name: "Continental Crash", recommendation: "Alguien lo comprará aunque no es tan valuado - Market" },
            { number: "TM258", name: "Dark Matter", recommendation: "Alguien lo comprará a buen precio - Market" },
            { number: "TM259", name: "Meltdown", recommendation: "Alguien lo comprará a buen precio - Market" },
            { number: "TM260", name: "Aqua Cut", recommendation: "Alguien lo comprará a buen precio - Market" },
            { number: "TM261", name: "Spirit Break", recommendation: "Alguien lo comprará a buen precio - Market" },
            { number: "TM180", name: "Sizzly Slide", recommendation: "Alguien lo comprará aunque no es tan valuado - Market" }
            ];
    

    const input = document.getElementById("tmInput");
    const resultsTable = document.getElementById("tmResults");

    input.addEventListener("input", function () {
        const query = input.value.toLowerCase().trim();
        resultsTable.innerHTML = "";

        if (query === "") return;

        const filteredData = tmData.filter(tm => 
            tm.number.toLowerCase().includes(query) ||
            tm.name.toLowerCase().includes(query)
        );

        filteredData.forEach(tm => {
            const row = document.createElement("tr");
            row.innerHTML = `<td>${tm.number} ${tm.name}</td><td>${tm.recommendation}</td>`;
            resultsTable.appendChild(row);
        });
    });
});
